version: '3.4'
services:
  api:
    image: '${DOCKER_REGISTRY-}api'
    container_name: book.api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - '5000:5000'
      - '5001:5001'
  book.database:
    image: 'postgres:latest'
    container_name: book.database
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=german
    volumes:
      - './.containers/books-db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
